App setup
Mylo16/Budget-App pull request #1
Opened 2023-08-19 19:56 UTC by Mylo16

### In this PR:
- I created the splash screen of my Ruby on Rails Budget-App
- I created the sign up and log in pages for the app
- I created the homepage 
- I created the transactions page
- I implemented the new category page
- I implemented the new transaction page
- I wrote unit and integration tests for the most important components
- Attached below is the description video on the app:

2023-08-19 21:05 UTC, tugsem requested changes
##  STATUS: REQUIRED CHANGES ♻️
Hello @Mylo16  👋 , 

Good job so far! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

![ Alt Text](https://media.giphy.com/media/l0MYC5rnAHehkVKRq/giphy.gif)
## Highlights 🚀 
✔️app works properly
✔️app tested thoroughly
✔️design guidelines mostly followed
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-19 21:05 UTC, tugsem commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p> -->
- [ ] As per the requirement for this capstone, you need to deploy your app using Render, Netlify or GitHub Pages and put the link here. Please do this.

2023-08-19 21:05 UTC, tugsem commented on README.md
> +
- [ ] As per the requirement for this capstone, please give an appropriate credit to [Gregoire Vella on Behance](https://www.behance.net/gregoirevella) the [author of the original design](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=), as required by the [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/)

2023-08-20 01:09 UTC, binhussen approved these changes
Hi @Mylo16 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- Stiched given design ✔️
- Well Stractured code✔️
- Used Git flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-26 09:51 UTC, merged